---
# General settings
general:
  n_available_cpu: 6
  broker_image: mininetfed:broker
  experiments_folder: experiments
  stop: auto # auto, cli, (None -> auto)

# Experiment settings
experiment:
  new_experiment: False
  experiment_name: 40_rounds_deev_fedAvg_TrainerHar_test_10_clients
  trainer_mode: random
  max_n_rounds: 40
  stop_accuracy: 0.97
  min_trainers: 4
  # server_client_args:
  #   encrypted: False
  #   debug: False
  #   n_clusters: 1

# Network settings
network:
  network_monitor_script: network_monitor.py
  network_monitor_image: mininetfed:client
  network_components: 1
  connections:
    - connection1: 1
      connection2: 2
      loss: 0
      delay: 0ms
      bw: 10

# Server settings
server:
  memory: 3000m
  vCPU_percent: 1000
  image: mininetfed:client
  connection: 1
  script: server/server.py

# Clients settings list
client_types:
  - amount: 4
    name: tipo1
    memory: 2600m
    vCPU_percent: 100
    image: mininetfed:client
    script: client/client.py
    connection: 1
    loss:
    delay:
    bw:
    # client_instantiation_args:
    #   encrypted: False
    #   debug: False
    #   n_clusters: 1
    #   fold: 0
  # - amount: 1
  #   name: tipo2
  #   memory: 1024m
  #   vCPU_percent: 15
  #   image: mininetfed:client
  #   script: client/client.py
  #   connection: 1
  #   loss: 0
  #   delay: 0ms
  #   bw: 20
