---
# General settings
general:
  n_available_cpu: 6
  broker_image: mininetfed:broker
  experiments_folder: experiments
  stop: auto # auto, cli, (None -> auto)

# Experiment settings
experiment:
  new_experiment: True
  experiment_name: teste_do_trainer_ckksfed
  trainer_mode: unbalanced
  max_n_rounds: 50
  stop_accuracy: 0.93
  min_trainers: 20
  # client_args:

# Network settings
network:
  network_monitor_script: network_monitor.py
  network_monitor_image: mininetfed:client
  network_components: 1
  connections:
    - connection1: 1
      connection2: 2
      loss: 0
      delay: 0ms
      bw: 10

# Server settings
server:
  memory: 4000m
  vCPU_percent: 100
  image: mininetfed:client
  connection: 1
  script: server/server.py

# Clients settings list
client_types:
  - amount: 20
    name: tipo1
    memory: 2048m
    vCPU_percent: 100
    image: mininetfed:client
    script: client/client.py
    connection: 1
    loss:
    delay:
    bw:

  # - amount: 1
  #   name: tipo2
  #   memory: 1024m
  #   vCPU_percent: 15
  #   image: mininetfed:client
  #   script: client/client.py
  #   connection: 1
  #   loss: 0
  #   delay: 0ms
  #   bw: 20
