---
# não implementado (pedir ajuda ao Jovane)
# Output metrics
metrics:
  - mean
  - accuracy

# General settings
general:
  absolute_path: false

# (atualmente são só switchs)
network_components: 1

# Network conections
# não implementado
conections:
  - conection1: 1
    conection2: 2
    type: (corrigir) # procurar endender melhor os tipos de conexões para implementar isso
    delay: 0.2
    loss: 0.01
    band_wdth: 200

# Server settings
server:
  memory: 256m
  CPU: (Corrigir) # não implementado
  image: johann:ubuntu
  volume: /flw
  conection: 1
  script: /server.py

# Clients settings list
client_types:
  - amount: 1
    name: tipo1
    memory: 512m
    CPU: (Corrigir) # não implementado
    image: johann:ubuntu
    volume: /flw
    script: /client.py
    conection: 1
    loss: 0
    bw: 10

  - amount: 1
    name: tipo2
    memory: 512m
    CPU: (Corrigir) # não implementado
    image: johann:ubuntu
    volume: /flw
    script: /client.py
    conection: 1
    loss: 0
    bw: 10
# Fazer um arquivo de exemplo bem comentado
#
