---
# não implementado (pedir ajuda ao Jovane)
metrics:
  - mean
  - accuracy

# Configurações gerais
general:
  absolute_path: false

# Número de componentes de rede (atualmente são só switchs)
network_components: 1

# Definição das conexões entre os componentes de rede
# não implementado
conections:
  - conection1: 1
    conection2: 2
    type: (corrigir) # procurar endender melhor os tipos de conexões para implementar isso
    delay: 0.2
    loss: 0.01
    band_wdth: 200

# Configurações do servidor
server:
  memory: 256m
  CPU: (Corrigir) # não implementado
  image: johann:ubuntu
  volume: /flw
  conection: 1
  script: /flower/servidorFlower.py

# Lista de tipo de clientes
client_types:
  - amount: 1
    name: tipo1
    memory: 512m
    CPU: (Corrigir) # não implementado
    image: johann:ubuntu
    volume: /flw
    model: /flower/clienteFlower.py
    conection: 1
    loss: 0
    bw: 10

  - amount: 1
    name: tipo2
    memory: 512m
    CPU: (Corrigir) # não implementado
    image: johann:ubuntu
    volume: /flw
    model: /flower/clienteFlower.py
    conection: 1
    loss: 0
    bw: 10
